from flask_wtf import FlaskForm
from wtforms import RadioField
#from . import db
SECRET_KEY = 'development'
class MyForm(FlaskForm):
    otazka0 = RadioField('Co znamená zkratka RAM?', choices=[(0, 'Random Access Memory'), (1, 'Read-Asynchronous Memory'), (2, 'Rewritable Access Memory'), (3, 'Rewritable Accessible Memory')], coerce=int)
    otazka1 = RadioField('Jaké součástky jsou naprosto nezbytné pro fungování počítače?', choices=[(0, 'Procesor, Základní deska, Monitor, Klávesnice'), (1, 'Procesor, Grafická karta, Zdroj, RAM'), (2, 'Základní deska, Procesor, RAM, Zdroj'), (3, 'Skříň, Monitor, Klávesnice, Myš')], coerce=int)
    otazka2 = RadioField('Mobilní telefon…', choices=[(0, 'Není počitač'), (1, 'Je počítač'), (2, 'Je speciálním zařízením odvozeným od počítače a proto se nedá považovat za počítač'), (3, 'Je nástupce počítače')], coerce=int)
    otazka3 = RadioField('Číslo 16 v osmičkové soustavě je…?', choices=[(0, '10000'), (1, '20'), (2, '24'), (3, '121')], coerce=int)
    otazka4 = RadioField('Jaký programovací jazyk používá Unreal Engine 4', choices=[(0, 'C#'), (1, 'Java'), (2, 'Python'), (3, 'C++')], coerce=int)
    otazka5 = RadioField('Jaký je rozdíl mezi SSD a HDD?', choices=[(0, 'SSD ukládá data v elektronické podobě zatímco v HDD jsou ukládána na el. mag. disku.'), (1, 'SSD ukládá data na el. mag. disk zatímco HDD v jsou uložená data v elektronické podobě.'), (2, 'SSD se používá v noteboocích, HDD ve stolních počítačích'), (3, 'SSD se více hodí na dlouhodobé uložení dat, kvůli své dlouhé životnosti')], coerce=int)
    otazka6 = RadioField('Kterou zkratku má logický součin?', choices=[(0, 'OR'), (1, 'XOR'), (2, 'AND'), (3, 'NOR')], coerce=int)
    otazka7 = RadioField('Co je to počítač?', choices=[(0, 'Např. kalkulačka'), (1, 'Zařízení pro zpracování dat pomocí předem vytvořeného programu'), (2, 'Zařízení, které se skládá z počítačové skříně, klávesnice a myši'), (3, 'Zařížení, které nemá turingovskou úplnost')], coerce=int)
    otazka8 = RadioField('Co je to Internet?', choices=[(0, 'Uzavřená počítačová síť'), (1, 'Celosvětový systém propojených počítačových sítí'), (2, 'Název souhrnu technologií pro počítačové sítě'), (3, 'Služby výhradně poskytující zábavu')], coerce=int)
    otazka9 = RadioField('Co znamená zkratka Wi-Fi?', choices=[(0, 'Wireless Fidelity'), (1, 'Wireless Fixture'), (2, 'Wireless Firewire'), (3, 'Nic, existuje jen jako chytlavý název')], coerce=int)
    otazka10 = RadioField('K čemu slouží Bluetooth?', choices=[(0, 'Výhradně pro poslech hudby'), (1, 'Bezdrátový přenos dat, zvuku atp.'), (2, 'Připojení k Internetu'), (3, 'Přenosu dat použitím kabelu nebo i bezdrátově')], coerce=int)
    otazka11 = RadioField('Herní engine je například…', choices=[(0, 'Numpy, Keras'), (1, 'Godot, Unreal Engine 3'), (2, 'JavaScript, C#'), (3, 'Steam, Epic Games')], coerce=int)
    otazka12 = RadioField('Co je to operační systém?', choices=[(0, 'Základní program počítače umožňující běh dalších programů'), (1, 'Např. BIOS'), (2, 'Veškerý software předinstalovaný na počítači'), (3, 'Základní program počítače sloužící výhradně pro komunikaci s hardwarem')], coerce=int)
    otazka13 = RadioField('Co znamená zkratka HTML?', choices=[(0, 'HyperText Machine Learning'), (1, 'HyperText Modular Language'), (2, 'HyperText Markup Language'), (3, 'HyperText Machine Language')], coerce=int)
    otazka14 = RadioField('Co je to kryptoměna?', choices=[(0, 'Unikátní token digitálního vlastnictví NFT'), (1, 'Druh šifrování'), (2, 'Měna s detailní historií tranksakcí'), (3, 'Typ digitální měny, která je tvořena elektronicky')], coerce=int)
    otazka15 = RadioField('V jakém programovací jazyku je napsaný Minecraft?', choices=[(0, 'PHP'), (1, 'Rust'), (2, 'Java'), (3, 'JavaScript')], coerce=int)
    otazka16 = RadioField('K čemu slouží kybernetika?', choices=[(0, 'Regulace, Technické řízení'), (1, 'Zabezpečení systému'), (2, 'Označení pro zločin na webu'), (3, 'Zpracování převodů mezi běžnou měnou a kryptoměnou')], coerce=int)
    otazka17 = RadioField('Kolik bajtů (byte) je jeden gigabajt (gigabyte)? Pozor na rozdíl mezi gibibyte a gigabyte!', choices=[(0, '1 000 000 000 000 B'), (1, '1 024 024 024 024 B'), (2, '1 073 741 824 B'), (3, '1 000 000 000 B')], coerce=int)
    otazka18 = RadioField('Jaké jsou dnes používané operační systémy na počítači?', choices=[(0, 'PowerShell'), (1, 'Unix, BSD'), (2, 'Windows, MacOS, Linux'), (3, 'MFT')], coerce=int)
    otazka19 = RadioField('Procesor je poskládán z: ', choices=[(0, 'Řadič, Registry, ALU, FPU'), (1, 'Hub, Switch, Bridge'), (2, 'Registry, CISC, Operand, FPU'), (3, 'ALU, RISC, Sběrnice, Řadič')], coerce=int)
    otazka20 = RadioField('Periferie jsou například…', choices=[(0, 'Herní konzole'), (1, 'Počítačová skříň, HDMI kabel'), (2, 'Klávesnice, tiskárna, myš'), (3, 'Grafická karta, procesor')], coerce=int)
    otazka21 = RadioField('Jak se jmenuje první vzniklý programovací jazyk?', choices=[(0, 'Plankalkül'), (1, 'Assembly'), (2, 'FORTRAN'), (3, 'Autocode')], coerce=int)
    otazka22 = RadioField('Co znamená HTTP Error 404?', choices=[(0, 'Conflict'), (1, 'No Content'), (2, 'Service Unavailable'), (3, 'Not Found')], coerce=int)
    otazka23 = RadioField('Co je to ray-tracing?', choices=[(0, 'Metoda výuživající zpětné sledování paprsku pro výpočet obrazů'), (1, 'Metoda výužívající fyzikální zákony o šíření energie prostoru pro výpočet obrazů'), (2, 'Metoda vyklesující scénu v uměleckém stylu'), (3, 'Metoda šířící světlo skrze objekt bez zkreslení')], coerce=int)
    otazka24 = RadioField('Které firmy vyrábí v dnešní době grafické karty?', choices=[(0, 'ATI, NVIDIA'), (1, 'SAMSUNG, SK HYNIX, Micron'), (2, 'Microsoft, IMB'), (3, 'Google, Facebook')], coerce=int)
